#!/bin/bash
echo 'preparing screenshots...';
rm -rf source/images/screens/composed.png;
convert source/images/screens/*.png -background gray -bordercolor gray -border 20x20 +append source/images/screens/composed.png;
echo 'screenshots are ready';
